name: mining_app
description: Eine einfache Mining-App mit AdMob und PayPal-Integration.
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.3.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  webview_flutter_android: ^3.3.1
  webview_flutter_wkwebview: ^3.18.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
